### PR TITLE
Revert "CSE Preprocessing and Partial Factorization"

### PR DESCRIPTION
**Pull request by zachetienne**
Reverts zachetienne/nrpytutorial#3

Unfortunately the latest commit breaks partial factorization support. For example we see:

`const double cf_dD0 = invdx0*(-2.0/3.0*cf_i0m1_i1_i2 + (1.0/12.0)*cf_i0m2_i1_i2 + (2.0/3.0)*cf_i0p1_i1_i2 + tmpFD1);`

### CODE REVIEW

**Comment by ksible** [comment]
I can't find that particular example or any example that wasn't factored. Did that example come from a section where partial factoring was disabled?

**Comment by zachetienne** [comment]
I cannot reproduce the above example after pulling latest master from your repo. I can see a problem with the SIMD version of this line of code. Here's line 528 of rhs_eval.h from running Tutorial-Start_to_Finish-BSSNCurvilinear-Two_BHs_Collide.ipynb:

`const REAL_SIMD_ARRAY cf_dD0 = MulSIMD(invdx0, FusedMulAddSIMD(cf_i0m2_i1_i2, tmpFDPart1__Rational_1_12, FusedMulSubSIMD(cf_i0p1_i1_i2, tmpFDPart1__Rational_2_3, FusedMulAddSIMD(cf_i0m1_i1_i2, tmpFDPart1__Rational_2_3, MulSIMD(cf_i0p2_i1_i2, tmpFDPart1__Rational_1_12)))));
`

**Comment by ksible** [comment]
I’ll clone my repo onto my desktop and see what happens after running that notebook.

Ken Sible
West Virginia University – Class of 2021
M.S. Student in Pure Mathematics
kjs0001@mix.wvu.edu | 724.678.8211

**Comment by ksible** [comment]
expr = cos(3*a - 3*b)*Rational(2, 3) - Rational(2, 3)*x - x**(-3)
expr, var_map = cse_preprocess(expr, ignore=True, factor=True)
_NegativeOne_*(_Rational_2_3*x + x**(-3)) + _Rational_2_3*cos(_Integer_3*(_NegativeOne_*b + a))

expr, var_map = cse_preprocess(expr, ignore=False, factor=True)
_NegativeOne_/x**3 + _Rational_2_3*(-x + cos(_Integer_3*(a - b)))

**Comment by zachetienne** [comment]
That looks fine for SIMD (where we might catch subtractions caused by factoring out NegativeOne), though I'm not sure how good it looks when SIMD is disabled. Do we get anything weird like

(x-y) -> -(-x+y)

from this approach?

**Comment by ksible** [comment]
The output with the ignore parameter disabled:
`_NegativeOne_/x**3 + _Rational_2_3*(-x + cos(_Integer_3*(a - b)))`

**Comment by zachetienne** [comment]
Looks good, please push when ready

**Comment by ksible** [comment]
https://github.com/zachetienne/nrpytutorial/pull/5

**Pull request merged**
